import React from 'react'
import Head from 'next/head'
import MercuryImg from '../../public/assets/planet-mercury.svg'
import MercuryInternal from '../../public/assets/planet-mercury-internal.svg'
import Planet from "components/Planet";
import Header from "components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Planet Facts Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Planet 
            planetName="MERCURY"
            Image={MercuryImg}
            Internal={MercuryInternal}
            overview="Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets. Mercury is one of four terrestrial planets in the Solar System, and is a rocky body like Earth."
            surfaceGeo="Mercury's surface is similar in appearance to that of the Moon, showing extensive mare-like plains and heavy cratering, indicating that it has been geologically inactive for billions of years. It is more heterogeneous than either Mars's or the Moon’s."
            interalStr="Mercury appears to have a solid silicate crust and mantle overlying a solid, iron sulfide outer core layer, a deeper liquid core layer, and a solid inner core. The planet's density is the second highest in the Solar System at 5.427 g/cm3 , only slightly less than Earth's density."
            planetLink="https://en.wikipedia.org/wiki/Mercury_(planet)"
            rotation="58.6 Days"
            revolution="87.97 Days"
            radius="2,439.7 KM"
            averageTemp="430°c"
            />
    </>
  )
}
